name: Scraper Loterías

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

# Añadir control de concurrencia
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.SCRAPER_WORKFLOW }}
        persist-credentials: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd scraper
        npm install axios
        npm install -D typescript@4.9.5 ts-node@10.9.1 @types/node
        
    - name: Run scraper
      run: |
        cd scraper
        npx ts-node scraper.ts
      
    - name: Commit and push if changes
      env:
        SCRAPER_WORKFLOW: ${{ secrets.SCRAPER_WORKFLOW }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git remote set-url origin https://x-access-token:${SCRAPER_WORKFLOW}@github.com/${{ github.repository }}
        git add src/assets/botes.json
        git add scraper/package*.json
        git status
        git diff --quiet && git diff --staged --quiet || git commit -m "Actualizar botes y dependencias [skip ci]"
        git push
